export const enum ChannelType {
	Direct = "DIRECT",
	Group = "GROUP"
}

export const enum Department {
	CONCEPT_AND_DESIGN = "CONCEPT_AND_DESIGN",
	ENVISAGE = "ENVISAGE",
	EVENTS_AND_WORKSHOPS = "EVENTS_AND_WORKSHOPS",
	EVOLVE = "EVOLVE",
	FINANCE = "FINANCE",
	OPERATIONS_AND_INFRASTRUCTURE_PLANNING = "OPERATIONS_AND_INFRASTRUCTURE_PLANNING",
	PUBLICITY = "PUBLICITY",
	QMS = "QMS",
	SHOWS_AND_EXHIBITIONS = "SHOWS_AND_EXHIBITIONS",
	SPONSORSHIP_AND_PR = "SPONSORSHIP_AND_PR",
	WEBOPS = "WEBOPS"
}

export const enum MemberPosition {
	COCAS = "COCAS",
	COORD = "COORD",
	CORE = "CORE",
	HEAD = "HEAD"
}