export const Departments = {
	WEBOPS: "WEBOPS",
	SPONSORSHIP_AND_PR: "SPONSORSHIP_AND_PR",
	SHOWS_AND_EXHIBITIONS: "SHOWS_AND_EXHIBITIONS",
	EVENTS_AND_WORKSHOPS: "EVENTS_AND_WORKSHOPS",
	OPERATIONS_AND_INFRASTRUCTURE_PLANNING: "OPERATIONS_AND_INFRASTRUCTURE_PLANNING",
	EVOLVE: "EVOLVE",
	ENVISAGE: "ENVISAGE",
	FINANCE: "FINANCE",
	CONCEPT_AND_DESIGN: "CONCEPT_AND_DESIGN",
	PUBLICITY: "PUBLICITY",
	QMS: "QMS"
};

export const Positions = {
	COORD: "COORD",
	HEAD: "HEAD",
	CORE: "CORE",
	COCAS: "COCAS"
};
